config/routes.rb
Reddlinks::Application.routes.draw do
  controller :sessions do
    get    'login' => :new
    post   'login' => :create
    delete 'logoff' => :destroy
  end

  controller :voting do
    post 'up'   => :up
    post 'down' => :down
  end

  resources :users

  resources :link_communities

  resources :communities

  resources :links

  controller :home do
    get ':order' => :index, as: "order"
    get 'c/:community' => :filter, as: "filter"
    get 'c/:community/:order' => :filter, as: "filter_order"
  end

  get "home/index"
  get "/links/:link_id/communities/new", to: "communities#not_related", as: "new_communities_to_link"

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @links = Link.all

    sort_links
  end

  def filter
    @community = Community.find_by_title(params[:community])
    @links = @community.links

    sort_links
    render 'index'
  end

  private
  def sort_links
    if params[:order]
      orderer = OrdererFactory.build params[:order].to_sym
      @links = orderer.order @links
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_entry.html.haml
.entry
  .number= index.to_s + "."
  -if session[:user_id]
    .vote-up= link_to "-", down_path(:link_id => link.id), :method => :post
    .rating= link.rating
    .vote-down= link_to "+", up_path(:link_id => link.id), :method => :post
  - else
    .rating= link.rating
  = link_to link.title, link.url
  %br
  = label_tag "Last updated: #{link.last_updated} by #{link.owner_name}"

app/views/home/index.html.haml
- if notice
  %p#notice= notice

%ul{:class => "filter-list"}
- if @community
  %li{:class => "filter-item"}= link_to "New", filter_order_path(community: @community.title, order: :new)
  %li{:class => "filter-item"}= link_to "Top", filter_order_path(community: @community.title, order: :top)
  %li{:class => "filter-item"}= link_to "Old", filter_order_path(community: @community.title, order: :old)
- else
  %li{:class => "filter-item"}= link_to "New", order_url(order: :new)
  %li{:class => "filter-item"}= link_to "Top", order_url(order: :top)
  %li{:class => "filter-item"}= link_to "Old", order_url(order: :old)
%ul
  - @links.each_with_index do |link, index|
    %li
      = render 'entry', link: link, index: index + 1