config/routes.rb
Reddlinks::Application.routes.draw do
  controller :sessions do
    get    'login' => :new
    post   'login' => :create
    delete 'logoff' => :destroy
  end

  controller :voting do
    post 'up'   => :up
    post 'down' => :down
  end

  resources :users

  resources :link_communities

  resources :communities

  resources :links

  controller :home do
    get ':order' => :index, as: "order"
    get 'c/:community' => :filter, as: "filter"
    get 'c/:community/:order' => :filter, as: "filter_order"
  end

  get "home/index"
  get "/links/:link_id/communities/new", to: "communities#not_related", as: "new_communities_to_link"

  root :to => 'home#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :title, :url, :user_id

  validates :title, :url, :user_id, presence: true
  validates :title, uniqueness: true

  belongs_to :user
  has_many :link_communities, dependent: :destroy
  has_many :votes, dependent: :destroy

  def owner_name
    user.name
  end

  def last_updated
    updated_at.strftime "%d.%m.%Y"
  end

  def rating
    votes.map(&:value).sum
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authorize  

  # GET /links
  # GET /links.json
  def index
    @links = Link.find_all_by_user_id current_user.id

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new
    @link.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.haml
= form_for @link do |f|
  - if @link.errors.any?
    #error_explanation
      %h2= "#{pluralize(@link.errors.count, "error")} prohibited this link from being saved:"
      %ul
        - @link.errors.full_messages.each do |msg|
          %li= msg
  =f.hidden_field :user_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/links/_owned.html.haml
%table
  %tr
    %th Community
    %th
  - @link.link_communities.each do |relation|
    %tr
      %td= relation.community.title
      %td= link_to "Remove", relation, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/links/edit.html.haml
%h1 Editing link

= render 'form'

= link_to 'Show', @link
\|
= link_to 'Back', links_path

app/views/links/index.html.haml
%h1 Listing links

%table
  %tr
    %th Title
    %th Description
    %th Url
    %th
    %th
    %th

  - @links.each do |link|
    %tr
      %td= link.title
      %td= link.description
      %td= link.url
      %td= link_to 'Show', link
      %td= link_to 'Edit', edit_link_path(link)
      %td= link_to 'Destroy', link, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %td= link_to 'Add community', new_communities_to_link_path(link)

%br

= link_to 'New Link', new_link_path

app/views/links/new.html.haml
%h1 New link

= render 'form'

= link_to 'Back', links_path

app/views/links/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @link.title
%p
  %b Description:
  = @link.description
%p
  %b Url:
  = @link.url
= link_to 'Add community', new_communities_to_link_path({"link_id"=>@link})
= render "owned"
= link_to 'Edit', edit_link_path(@link)
\|
= link_to 'Back', links_path