config/routes.rb
Reddlinks::Application.routes.draw do
  controller :sessions do
    get    'login' => :new
    post   'login' => :create
    delete 'logoff' => :destroy
  end

  controller :voting do
    post 'up'   => :up
    post 'down' => :down
  end

  resources :users

  resources :link_communities

  resources :communities

  resources :links

  controller :home do
    get ':order' => :index, as: "order"
    get 'c/:community' => :filter, as: "filter"
    get 'c/:community/:order' => :filter, as: "filter_order"
  end

  get "home/index"
  get "/links/:link_id/communities/new", to: "communities#not_related", as: "new_communities_to_link"

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def authorize
    unless current_user
      redirect_to login_path, alert: "You must login"
    end
  end

  def current_user
    User.find_by_id(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_login.html.haml
= form_tag("/login/") do
  .field
    = label_tag :name, "Username"
    = text_field_tag :name, params[:name]
  .field
    = label_tag :password, "Password"
    = password_field_tag :password, params[:password]
  .field
    = link_to "register", new_user_path
  .actions
    = submit_tag 'Login'

app/views/application/_menu.html.haml
%h3 Menu
%ul
  %li= link_to "Home", root_path
  %li= link_to "My links", links_path
  %li= link_to "My communities", communities_path
  %li= link_to "Logoff", logoff_path, :method => :delete

app/views/application/_side.html.haml
%p
  %strong Menu

%ul
  %li= link_to "Home", root_path
  %li= link_to "My links", links_path
  %li= link_to "My communities", communities_path
  %li= link_to "Logoff", logoff_path, :method => :delete