config/routes.rb
Reddlinks::Application.routes.draw do
  controller :sessions do
    get    'login' => :new
    post   'login' => :create
    delete 'logoff' => :destroy
  end

  controller :voting do
    post 'up'   => :up
    post 'down' => :down
  end

  resources :users

  resources :link_communities

  resources :communities

  resources :links

  controller :home do
    get ':order' => :index, as: "order"
    get 'c/:community' => :filter, as: "filter"
    get 'c/:community/:order' => :filter, as: "filter_order"
  end

  get "home/index"
  get "/links/:link_id/communities/new", to: "communities#not_related", as: "new_communities_to_link"

  root :to => 'home#index'

end

app/models/community.rb
class Community < ActiveRecord::Base
  NO_WITESPACES = /^[\S]+$/

  attr_accessible :description, :title, :user_id

  validates :title, :user_id, presence: true
  validates :title, uniqueness: true
  validates :title, format: { :with => NO_WITESPACES }

  belongs_to :user
  has_many :link_communities

  before_destroy :ensure_not_referenced_by_any_link_comminity

  def not_related?(link)
    link_communities.none? { |reference| reference.link_id == link.id } 
  end

  def links
    link_communities.map(&:link)
  end

  private

  def ensure_not_referenced_by_any_link_comminity
    if link_communities.empty?
      true
    else
      errors.add(:base, 'Link reference present')
      false
    end
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_filter :authorize

  def not_related
    @link = Link.find(params[:link_id])
    @communities = Community.all.find_all { |community| community.not_related?(@link) }
  end

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.find_all_by_user_id current_user.id

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @communities }
    end
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    @community = Community.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @community }
    end
  end

  # GET /communities/new
  # GET /communities/new.json
  def new
    @community = Community.new
    @community.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @community }
    end
  end

  # GET /communities/1/edit
  def edit
    @community = Community.find(params[:id])
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(params[:community])

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render json: @community, status: :created, location: @community }
      else
        format.html { render action: "new" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /communities/1
  # PUT /communities/1.json
  def update
    @community = Community.find(params[:id])

    respond_to do |format|
      if @community.update_attributes(params[:community])
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community = Community.find(params[:id])
    @community.destroy

    respond_to do |format|
      format.html { redirect_to communities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.haml
= form_for @community do |f|
  - if @community.errors.any?
    #error_explanation
      %h2= "#{pluralize(@community.errors.count, "error")} prohibited this community from being saved:"
      %ul
        - @community.errors.full_messages.each do |msg|
          %li= msg
  =f.hidden_field :user_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/communities/edit.html.haml
%h1 Editing community

= render 'form'

= link_to 'Show', @community
\|
= link_to 'Back', communities_path

app/views/communities/index.html.haml
%h1 Listing communities

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @communities.each do |community|
    %tr
      %td= community.title
      %td= community.description
      %td= link_to 'Show', community
      %td= link_to 'Edit', edit_community_path(community)
      %td= link_to 'Destroy', community, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Community', new_community_path

app/views/communities/new.html.haml
%h1 New community

= render 'form'

= link_to 'Back', communities_path

app/views/communities/not_related.html.haml
%p#notice= notice

%h1 Listing communities

%table
  %tr
    %th Title
    %th Description
    %th

  - @communities.each do |community|
    %tr
      %td= community.title
      %td= community.description
      %td
        = form_for LinkCommunity.new do |f|
          = f.hidden_field :community_id, value: community.id
          = f.hidden_field :link_id, value: @link.id

          = f.submit 'Add'

%br

= link_to 'Back', links_path

app/views/communities/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @community.title
%p
  %b Description:
  = @community.description

= link_to 'Edit', edit_community_path(@community)
\|
= link_to 'Back', communities_path